version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: matrimony-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8220
      MYSQL_DATABASE: sriang
    volumes:
      - matrimony-db:/var/lib/mysql
    networks:
      - matrimony-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: matrimony-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - matrimony-network
    volumes:
      - ./backend/gallery:/app/gallery
      - ./backend/kundli:/app/kundli

  frontend:
    build:
      context: ./frontend
    container_name: matrimony-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE: ""
      BASE_URL: /api
      API_BASE_URL: /api
    depends_on:
      - backend
    networks:
      - matrimony-network

networks:
  matrimony-network:
    driver: bridge

volumes:
  matrimony-db:

